title: Movimento Resultado
description: Pela União e Solução
lang: pt-BR

theme: jekyll-theme-slate

url: https://movimentoresultado.github.io

nav:
  - title: Início
    url: /
  - title: Manifesto
    url: /manifesto/

header_pages:
  - manifesto.md
